### ISSUE TITLE
Inconsistency due to scope(status=Active)

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#211]
There are still place in pykechain where, if a scope is hidden, some action will not be performed. For example:
In activity.py on line 241:
`                project = self._client.scope(self._json_data['scope']['name'])
`
This line gets triggered when you are trying to edit the assignees of an activity. But if the scope is hidden, then this will return a NotFoundError("No scope fits criteria"). This is because the status argument has "ACTIVE" as default. This confuses the user as he earlier retrieved the scope without problems. 

Fix for that:
line 241 needs to be changed to: 
` project = self._client.scope(self._json_data['scope']['name'], status=None)`

This issue might occur in other places as well.

**Comment by jberends** [comment]
this is indeed incorrect. Let us fix this in a point release 1.12

**Comment by jberends** [comment]
in 1.12.8
