### ISSUE TITLE
Using Part.update(update_dict={}) with only one attachment property gives a runtime error 

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#222]
update() method can be found in part.py on line 426

It has an if-else clause, and if there is only one property, the else clause is accessed, which attempts to set the value of an attachment property, but that raises a RuntimeError

Another related issue
On Part.add_with_properties(update_dict={}), if there is one attachment property, then the attachment will not be correctly added.

**Comment by raduiordache** [comment]
@jberends I can think of an easy fix, but I believe we should maybe rebuild these functions a bit. Unnecessary if-else clauses in my opinion.

**Comment by thendrich** [comment]
+1

**Comment by raduiordache** [comment]
Just re-tested this in the new PIM3, the problem is not valid anymore. Finally, this issue can be closed.
