### ISSUE TITLE
Populate_descendants does not work for part models

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#320]
- in part.py line 709:
descendants_flat_list = list(self._client.parts(pk=self.id, descendants='children', batch=batch))'
- should look like this:
descendants_flat_list = list(self._client.parts(pk=self.id, category=self.category, descendants='children', batch=batch))'

Cause .parts() has category set as instance by default. So using model.populate_descendants() will find no descendants because it will only check for instances.

**Comment by jberends** [comment]
in 2.2
