### ISSUE TITLE
create_property() in client.py uses an outdated default property_type

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#326]
Need to refactor it to use create_property(property_type=PropertyType.CHAR_VALUE) from the enums

Add a test for this in test_creation_of_all_property_model_types

Note to self: check if any fixes should be applied on the Pykechain training on demo.ke-chain

**Comment by jberends** [comment]
Yeah indeed. Just need to create a checker and mapper in case they only privide the shortcut instead of the *_VALUE

**Comment by jberends** [comment]
released in 2.2.1
