### ISSUE TITLE
Using Activity2.siblings() I retrieve the entire list of activities, not its direct brothers and sisters

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#332]
In the following code you can see the result of .siblings()

I would expect to only retrieve 2 activities, however it returns all.

![image](https://user-images.githubusercontent.com/26489981/40917092-4ea1dcfc-6802-11e8-9a1b-37f8952f1375.png)

**Comment by jberends** [comment]
released in 2.2.3
