### ISSUE TITLE
Add a Part.move() function 

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#343]
The purpose of this function would be to copy-paste or cut-paste the part instance/part model from under a parent and moving it to another parent, with (optionally) all the values of its properties and the sub-tree. 

Based on the [ICT-549](https://atlas.ke-works.net/jira/browse/ICT-549) ticket filed by Stefan. 

However, I am not sure we should implement this in Pykechain as it is not a KE-chain action by itself or just have it as a separate script (in which of course, we are using Pykechain). What do you think, @jberends ?

**Comment by jberends** [comment]
I would create the sequence in `helpers.py` and import this into the `Part.move(*args, delete_original=True, **kwargs)`.

**Comment by jberends** [comment]
released as 2.3.0
