### ISSUE TITLE
Setting the selection options on a single-select list property overwrites build-in options dict, clearing validators.

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#446]
Perform the following action, to enter a new list of single-select list options to the property model:
`prop.options = ['a', 'b', 'c']`
This action should set the options list, not the Property class _options dict. However, these are identical in the SingleSelectList class. 
Resolution: Rename the current options list property in the SSL class from `_options` to `_value_options` or something equivalent.

**Comment by jberends** [comment]
released in 2.5.4

**Comment by JelleBoersma** [comment]
I still have the same issue on our dk-test.ke-chain.com.
The Digitaal Keuren module sets new select-list options, clearing the required-field validators.

**Comment by JelleBoersma** [comment]
Closing issue, has not been seen lately.
