### ISSUE TITLE
PIM2 - proxy_model() function does not exist

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#453]
I am using proxy_model() in my scripts, but since proxy_model() was not translated to Part2, then it is using the one in Part. However, "proxy" was renamed in the "_json_data" dict, therefore the script believes that the respective part is not a proxy. See screeshots below.

**Comment by raduiordache** [comment]
![screenshot from 2019-02-28 15-02-31](https://user-images.githubusercontent.com/25708342/53572080-b45bd480-3b6a-11e9-98a6-2ac79e8e4141.png)
![screenshot from 2019-02-28 15-06-23](https://user-images.githubusercontent.com/25708342/53572081-b45bd480-3b6a-11e9-80e4-0e2ce2a9f4a7.png)

**Comment by jberends** [comment]
fixed in kec3 branch
