### ISSUE TITLE
In clone scope: the assertion on start_date is incorrect: It uses due_date.tzinfo instead of start_date.tzinfo

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#459]
if **start_date** is not None:
            if isinstance(**start_date**, datetime.datetime):
                if not **due_date**.tzinfo:
                    warnings.warn("The **duedate** '{}' is naive and not timezone aware, use pytz.timezone info. "
                                  "This date is interpreted as UTC time.".format(start_date.isoformat(sep=' ')))
                data_dict['start_date'] = start_date.isoformat(sep='T')
            else:
                raise IllegalArgumentError('Start date should be a datetime.datetime() object')

**Comment by bastiaanbeijer** [comment]
![image](https://user-images.githubusercontent.com/26489981/54816746-54ea7380-4c95-11e9-8a0a-98642e6a5523.png)

**Comment by jberends** [comment]
Which file, which branch?

**Comment by bastiaanbeijer** [comment]
In the PIM2-branch

git+https://github.com/KE-works/pykechain.git@PIM2-branch#egg=pykechain

**Comment by jberends** [comment]
incorporated in pim2 branch - see PR #411
