### ISSUE TITLE
standardize (and create guidelines for) pykechain architecture

### ISSUE THREAD

**Issue by wilcoschoneveld** [KE-works/pykechain#48]
Since pykechain is expanding rapidly, we might want to establish some guidelines regarding the architecture. This would also involve refactoring the current code to follow these guidelines.

Remarks regarding the codebase:
- The `Client` has a private `_request` method and is responsible for building requests (e.g. `Client.activites` and `Client.create_part`), however sometimes this is violated; e.g. `Property.delete` and `Activity.configure` build a request themselves.
- Most of the `APIError`s do not include additional information (e.g. why could a new activity not be created?)

**Comment by wilcoschoneveld** [comment]
I'm not sure if improvements are needed and worthwhile at all... i'm investigating

**Comment by jberends** [comment]
My thoughts:
* APIErrors indeed are mostly 'dump here' buckets for exceptions. We could easily improve this by investing time in the request, response, exceptions handling flow before returning control back to the custom method. I am thinking of all the `r= self._requests(...); if r.status_code != 200 ...` codes we see all over the client implementation
* I believe that custom enhancements such as notebook renderers should be defined outside the client
* although the client has some magic inside it is very practical for the enduser. Most usecase I see move very quickly from `client=Client() -> project = client.scope(...) -> project.parts(...)`

**Comment by wilcoschoneveld** [comment]
I also don't really like the new `add_with_properties` function because it's pretty specialized and can be done with two separate calls. Is the speedup for using a single call significant?

**Comment by wilcoschoneveld** [comment]
I stumbled upon http://python.apichecklist.com/. Might be a good idea to consider some of the ideas in there.

**Comment by jberends** [comment]
#stale discussion
