### ISSUE TITLE
Expose filename of the kecpkg within a Service as an attribute

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#480]
Currently we can only retrieve the name of the kecpkg file through the `._json_data` of a Service object. This filename is necessary to download-and-reupload the kecpkg. This functionality is required in the Digitaal Keuren application.

**Comment by jberends** [comment]
similar to the `AttachmentProperty.filename` property/mehtod.

**Comment by jberends** [comment]
released 2.5.7
