### ISSUE TITLE
detach jupyter specific renderings

### ISSUE THREAD

**Issue by wilcoschoneveld** [KE-works/pykechain#49]
I am thinking about moving all `_repr_html` stuff to [kenotebook](https://git.ke-works.net/wilco-schoneveld/kenotebook), and inject the renderers on load. This makes jupyter notebook specific stuff independent of base pykechain.

**Comment by jberends** [comment]
This is good. I agree on this route. Base pykechain is mature enough to do this. Is in alignment with the other proposals.

**Comment by jberends** [comment]
stale
