### ISSUE TITLE
add KE-chain user triggered execution of pykechain code

### ISSUE THREAD

**Issue by wilcoschoneveld** [KE-works/pykechain#51]
In order to fully support automation in KE-chain it should be possible to execute pykechain code with the push of a button.

I want to prototype the following setup:
- Create a function with a predefined signature
- Register the function to a task, by listening to a specific event on the websocket
- The event triggers execution of the function (i.e. user presses 'Run' in task)

Additional enhancements could include automated registrations of scripts, KE-node style maybe?

**Comment by jberends** [comment]
I am curious to see how we could implement 'webhooks' using kevents (or kehooks). Basically the webhook is called on the kevent (or kehook) websocket channel to all registered services. 

We have already KEC2 code available for websocket basic authentication (need token auth as well) for the new KE-node. But I prefer to move details of that discussion to jira.

In the pyke case I would propose to alter your proposed implementation in the following way

* make a pykechain 'keep alive' deamon listening on kevents websocket channel of activity_ids (needs auth now)
* based on a change in the activity_id execute inner function
* have one or more of these 'microservices' runners alive on a pc

**Comment by wilcoschoneveld** [comment]
@jberends I've assigned this to you for now

**Comment by jberends** [comment]
Implemented this as lightweight kenode in our private repo.
