### ISSUE TITLE
Bug in add_html_widget() function for new PIM3 branch: custom_title = None breaks.

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#525]
Right now no title/custom_title results in a 404 error. (title can't be blank). 

Solution:

Instead of:
`default_title = None
`
We should provide a default title, as it's required to create a widget with a title.
`default_title=WidgetTypes.HTML`

**Comment by jberends** [comment]
If customTitle is provided use that as title, otherwise use class.__name__

**Comment by raduiordache** [comment]
@bastiaanbeijer - this should work now, can you check?
I have also renamed custom_title as just title in the context of adding a widget
