### ISSUE TITLE
Add functionality to update/create prefilters/excluded props etc to FILTERED_GRID widget in widget_manager functions

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#526]

**Comment by raduiordache** [comment]
@bastiaanbeijer - there are now 2 extra arguments on add_filteredgrid_widget(prefilters, excluded_propmodels)

The documentation is not there, but they work similar to how they work on the MultiReferenceProperty

**Comment by raduiordache** [comment]
#TODO - write documentation

**Comment by raduiordache** [comment]
Done
