### ISSUE TITLE
cross reference property in PIM3 is not saving the scope_id in the value_options

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#535]
see: pykechain/models/property2_multi_reference.py:107
see: pykechain.models.property2_multi_reference.MultiReferenceProperty2.value

TODO: extract scope_id from the 'value_to_set' and putsh this onto the `value_options` if it is a model.

**Comment by JelleBoersma** [comment]
Added tests in 86cc1063c13705aef291f0ec484ff3e01f130343
