### ISSUE TITLE
Add progressBarSettings to the widgetmanager.add_metapanel_widget function

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#540]
For example
progressBarSettings={"customHeight": 10,
                                                                 "showProgressText": True,
                                                                 "colorNoProgress": "#eee",
                                                                 "colorInProgressBackground": "#eee",
                                                                 "colorCompleted": "rgba(51, 148, 71, 1)",
                                                                 "colorInProgress": "rgba(51, 148, 71, 1)"}

**Comment by raduiordache** [comment]
superb issue even more superbly fixed
