### ISSUE TITLE
Add copy and/or move Property functionality

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#545]
It would be nice to have a function (most likely on the `Property2` class) to copy and/or move the `Property` to another `Part` model. 

Currently, the code in our DK module has to account for all the _content_ of a Property when copying, which should preferably be handled by pykechain. Think of content such as single-select options, validators, description, units, etc. Whenever the `Property` implementation changes in the future, we have to make specific modifications when writing such copy-property code.

**Comment by raduiordache** [comment]
"It would be nice" has turned into "it is nice". Thank me later.
