### ISSUE TITLE
Add signature & card widgets to WidgetTypes enum

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#547]

**Comment by jberends** [comment]
- [X] add signature and card to the enums
- [X] add `SignatureWidget` model and `CardWidget` model (incl validations)
- [ ] create `WidgetsManager.add_signature_widget()` method
- [ ] create `WidgetsManager.add_card_widget()` method

**Comment by raduiordache** [comment]
Added Signature Widget

**Comment by raduiordache** [comment]
Added Card Widget, this story is now concluded.
