### ISSUE TITLE
Create fileExtensionValidator and fileSizeValidator for AttachmentProperty in PIM3

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#573]

**Comment by bastiaanbeijer** [comment]
See:
https://agile4.ke-chain.com/v3/#/scopes/c32130c1-8140-4c87-b1d6-8e5e01da674e/activities/fa795752-58d1-4956-8359-e2503dd4bade

**Comment by bastiaanbeijer** [comment]
File "/usr/local/lib/python3.5/site-packages/pykechain/models/part2.py", line 94, in __init__
    for p in sorted(json['properties'], key=lambda p: p.get('order', 0))]
  File "/usr/local/lib/python3.5/site-packages/pykechain/models/part2.py", line 94, in <listcomp>
    for p in sorted(json['properties'], key=lambda p: p.get('order', 0))]
  File "/usr/local/lib/python3.5/site-packages/pykechain/models/property2.py", line 118, in create
    return AttachmentProperty2(json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pykechain/models/property2.py", line 60, in __init__
    validate(self._options, options_json_schema)
  File "/usr/local/lib/python3.5/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'fileSizeValidator' is not one of ['booleanFieldValidator', 'evenNumberValidator', 'noneValidator', 'numericRangeValidator', 'oddNumberValidator', 'regexStringValidator', 'requiredFieldValidator', 'singleReferenceValidator']

Failed validating 'enum' in schema['properties']['validators']['items']['properties']['vtype']:
    {'enum': ['booleanFieldValidator',
              'evenNumberValidator',
              'noneValidator',
              'numericRangeValidator',
              'oddNumberValidator',
              'regexStringValidator',
              'requiredFieldValidator',
              'singleReferenceValidator'],
     'type': 'string'}

On instance['validators'][1]['vtype']:
    'fileSizeValidator'

**Comment by jberends** [comment]
@bastiaanbeijer -- removed customer specific comments in this public forum.

**Comment by jberends** [comment]
we deployed pykechain 3.0.2 to production to temporary deals with the filesize and fileextension validators.
