### ISSUE TITLE
add feature to configure the activity using pykechain (association api)

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#58]
* analog the the 'configure' of a task
* use the api to write the inputs, outputs configuration to an association

see testcode snippet from KEC2::
``` python
association1 = Association.objects.get(activity=activity1)
response = self.SUPERclient.put("/api/associations/{}".format(str(association1.id)),
                                        dict(inputs=[self.prop_model1.id, self.prop_model1.id],
                                             outputs=[self.prop_model1.id]))
```
you might want to use the `/api/associations?activity=<>` to get the association of an activity. Other way is to see if it is listed on an activity response itself. 

`GET /api/activities/6ff02812-5dee-4960-9807`

``` json
{
    "results": [
        {
            "id": "6ff02812-5dee-4960-9807",
            ...
            "configuration": "3fb65cbf-cefe-43dd-ba68",
            "status": "OPEN",
           ...
            "association_id": "3fb65cbf-cefe-43dd-ba68",
            "activity_class": "UserTask",
            "widget_config": null
        }
    ]
}
```

This is either the `configuration` or the `association_id` (the same)

**Comment by wilcoschoneveld** [comment]
This was already implemented in #24, right?
