### ISSUE TITLE
Catch update-dict with non-serialized values for `update` and `add_with_properties` methods of `Part2` class. 

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#590]
If the update-dict to either of these methods contains values not suited for bulk-update, these values should be caught and inserted separately. 

For example, the file-path of an attachment to be uploaded to an `AttachmentProperty` must be send via an `upload` method/end-point, not via the serialized JSON.

**Comment by jberends** [comment]
in 3.1.2
