### ISSUE TITLE
widget.copy() and .move() do not copy widget title properly

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#607]
Widget method `copy` simply uses `client.create_widget` to construct a 2nd widget. Method `move` calls `copy`.

However, `create_widget` parses the title, removing `None` or empty string `""`. This has to be rewritten to either allow a null-value, or `copy` should no longer use `create_widget`.

**Comment by raduiordache** [comment]
@JelleBoersma - Sorry, I couldn't really reproduce this. I tried with multiple widget types, including MultiColumn widgets, including widgets with or without titles inside the multicolumn widget and everything was copied correctly. I will leave this open for now, but do let me know if it pops up again.

**Comment by raduiordache** [comment]
Note: this was not a bug in Pykechain, but a problem in DK.
