### ISSUE TITLE
copy-move of multiple models to 1 parent causes duplicate instances if the model is `1-or-more`

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#636]
For `1-or-more` Part models, the copy-move function takes the auto-created first instance into account. However, this is tracked by logging which Part instance `parent_id` has been targeted for the model. 2 issues:

- I can copy multiple models to the same parent, so log the `model_id` instead.
- During a single Python session I can call copy-move multiple times: tracking of the copied instances will not work in a global list: track per function call instead.

**Comment by JelleBoersma** [comment]
Original code snippet:

![image](https://user-images.githubusercontent.com/41430092/70913771-f0d3c080-2016-11ea-9b76-3438e7095d1b.png)

**Comment by jberends** [comment]
3.2.3
