### ISSUE TITLE
Test framework is unstable and not easily extended

### ISSUE THREAD

**Issue by wilcoschoneveld** [KE-works/pykechain#64]
Requirements for testing:
- Running tests should be possible with and without a KE-chain server
- (ofcourse pykechain actual usage is limited to having access to a KE-chain server)
- Tests should cover over 90% of the pykechain code base, including functionality that interacts with a KE-chain

Current problems:
- Not all tests run with the pycharm test suite runner
- Sometimes 'betamax requests can not be found' errors when running tests (even though request is recorded)
- Scope name of test project is not consistent
- ... [in progress]

**Comment by wilcoschoneveld** [comment]
Requirements for testing:
- Running tests should be possible with and without a KE-chain server
- (ofcourse pykechain actual usage is limited to having access to a KE-chain server)
- Tests should cover over 90% of the pykechain code base, including functionality that interacts with a KE-chain

**Comment by wilcoschoneveld** [comment]
I'm going to create a custom pykechain fixture in KE-chain which we can use for testing purposes

**Comment by jberends** [comment]
See PR #65

**Comment by jberends** [comment]
stale
