### ISSUE TITLE
implement bulk-update for properties

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#663]
See the (new) `/api/v3/properties/bulk_update` endpoint

**Comment by JelleBoersma** [comment]
- [ ] implement API
- [ ] Create `client` method
- [ ] Create test(s)
- [ ] Facilitate use of the new method (instead of having to build a dict/json by hand)

**Comment by jberends** [comment]
goed werk!

**Comment by jberends** [comment]
3.4.0
