### ISSUE TITLE
Bug hunt

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#675]
- [x] Uploading to attachment properties should update `value` attribute.
- [x] Test for new team API entry-point for `clone_scope` functionality.
- [x] Simplify `Property` tests

**Comment by JelleBoersma** [comment]
- [ ] Pass `kwargs` from WidgetManager factory methods on into the Client's `create_widget` method.

**Comment by jberends** [comment]
3.4.0
