### ISSUE TITLE
Get documentation up to date

### ISSUE THREAD

**Issue by wilcoschoneveld** [KE-works/pykechain#69]
I noticed something missing:
* autoclass:: pykechain.models.ReferenceProperty

And verify all else is ok.

**Comment by jberends** [comment]
yup indeed. I also fixed the `part.edit()` in the meantime in commit [3cda08ce](/KE-works/pykechain/commit/ff77a78e2e82701f0906bb57b43c562e3cda08ce)

**Comment by jberends** [comment]
I asked tijl to make a 'getting started' guide as he is now ... getting started with pykechain. He is recording each step from making a virtualenv with jupyter notebooks onto interacting with a KE-chain scope.

**Comment by thendrich** [comment]
Hi @jberends , I made that getting started guide, how will it be included? In the readthedocs? @wilcoschoneveld ? 
Let me know and I can send it to you. I focused on setting it up for windows, since I'm on windows and most of the pyke audience will be in windows environments as well..

**Comment by thendrich** [comment]
@wilcoschoneveld @jberends something like this:

[pyke getting started.txt](https://github.com/KE-works/pykechain/files/912349/pyke.getting.started.txt)

**Comment by jberends** [comment]
Hi Tijl, I will process this and ensure it will be included in the next release docs.

**Comment by jberends** [comment]
in the 1.6.0 release
