### ISSUE TITLE
`Service` is missing the scope_id it belongs to

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#709]
scope_id attribute is shown as "None"

@JelleBoersma - if you have time, can you check what is going wrong here? We noticed this in the VMAP project. In pykechain version 3.0.2 it works fine, but in the newer ones it doesn't.

**Comment by JelleBoersma** [comment]
@raduiordache The scope ID is not in the KE-chain response, nothing changed in Pykechain since October 2019.

**Comment by JelleBoersma** [comment]
Found the culprit in the additional API parameters, will push a fix.

**Comment by raduiordache** [comment]
Thanks a lot, @JelleBoersma !
