### ISSUE TITLE
Add ability to empty a reference part property (no id selected)

### ISSUE THREAD

**Issue by raduiordache** [KE-works/pykechain#76]

**Comment by jberends** [comment]
Backend prevents this for the moment... we need to wait until this is possible in the API

**Comment by raduiordache** [comment]
@BennievanderWel - how much time would this take to be implemented? AWARD phase 3 will commence soon and this is one of the features I would like to introduce asap.

**Comment by raduiordache** [comment]
I have realized this was not an issue in Production, but only in RND. And now it has been fixed and merged. This issue can now be closed.
