### ISSUE TITLE
Retrieve related objects (parts/properties/proxies etc)

### ISSUE THREAD

**Issue by thendrich** [KE-works/pykechain#79]
Things I'd like to do:

- Retrieve the model of an instance
- Retrieve the instances of a model
- Retrieve the proxies of a catalog model
- Retrieve the catalog model of proxy
- Retrieve the (direct) properties of a part instance
- Retrieve the (direct) properties of a part model

This way, I can lookup sets of parts/properties and act on them (e.g. configure them). Currently, without the above, it's difficult to do more complex operations since retrieving the right parts is difficult.

**Comment by jberends** [comment]
> Retrieve the model of an instance
included in 1.6.0 using the `Part.model()`
see: http://pykechain.readthedocs.io/en/latest/api/models.html#pykechain.models.Part.model

> Retrieve the instances of a model
possible already by using: `project.parts(model=<part_model>)`
see: http://pykechain.readthedocs.io/en/latest/api/client.html#pykechain.Client.parts

> Retrieve the (direct) properties of a part instance
> Retrieve the (direct) properties of a part model
possible using `part.properties`, this returns a list of property objects

Will update the documentation for this

What remains 

- [ ] Retrieve the proxies of a catalog model
- [ ] Retrieve the catalog model of proxy

**Comment by raduiordache** [comment]
@jberends I have added the possibility to retrieve the parts to choose from a reference property, can you quickly check it out?

**Comment by raduiordache** [comment]
Also added the method that retrieves the catalog model of a proxy.

**Comment by jberends** [comment]
this will be released in 1.7
