### ISSUE TITLE
Add option DASHBOARD to widget_type

### ISSUE THREAD

**Issue by bastiaanbeijer** [KE-works/pykechain#869]
File "/usr/local/lib/python3.6/site-packages/pykechain/models/input_checks.py", line 98, in check_enum
    key, enum.__class__.__name__, value, type(value), enum.values()))
pykechain.exceptions.IllegalArgumentError: `widget_type` must be an option from enum type, "DASHBOARD" (<class 'str'>) is not.
Choose from: ['ATTACHMENTVIEWER', 'CARD', 'FILTEREDGRID', 'HTML', 'JSON', 'METAPANEL', 'MULTICOLUMN', 'NOTEBOOK', 'PROGRESS', 'PROPERTYGRID', 'SCOPE', 'SERVICE', 'SIGNATURE', 'SUPERGRID', 'TASKNAVIGATIONBAR', 'TASKS', 'THIRDPARTY', 'UNDEFINED', 'WEATHER']

**Comment by raduiordache** [comment]
Fixed by #873
