### ISSUE TITLE
retrieve all models and parts related to an activity (activity_id)

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#96]
For future needs we want to restrict parts and model updated restricted to the scope of an activity_id. For this we need all the parts that are 'configured' in an activity and available to work on.

**Comment by thendrich** [comment]
+1 also very handy for general KEC scripting

**Comment by jberends** [comment]
ensure to make a method that only retrieves the models to address #101

**Comment by jberends** [comment]
proto code

```
activity_models, activity_instances = activity.associated_parts()  --> returns a tuple with 2 partsets
```

**Comment by jberends** [comment]
there is already a method in `Activity.parts()` to retrieve parts associated. Used this one to retrieve both models and instances in a single go.

**Comment by jberends** [comment]
see the #123 pull requests

**Comment by jberends** [comment]
Will be released in 1.8

**Comment by raduiordache** [comment]
@jberends 
I have found some issues in the tests of this functionality, mainly in the use of assertTrue(), which checks whether an expression is true, and does not accept two parameters. I have adapted this in #149 , but I would ask you to review these adaptions.

**Comment by jberends** [comment]
okay inside 1.10.1 then
