### ISSUE TITLE
Customize a task using pykechain

### ISSUE THREAD

**Issue by thendrich** [KE-works/pykechain#97]
Use pykechain to customize a given task by feeding it the customization json. If the pyke developer handles this well, he can configure & customize many tasks in a row using the same customization blueprint

**Comment by jberends** [comment]
We need to make sure that we only support the API not the creation of the JSON itself. There will be no validation on the KE-chain side other than the 'form' of the JSON (is it a string, and is it valid JSON). It is up to KEC to parse. API on the KEC side may change any time.

api endpoint to use: `/api/widget_config`

**Comment by thendrich** [comment]
+1 that will do!

If we want to precreate the json in some way, we can always program that ourselves.

**Comment by jberends** [comment]
Included in 1.7.0
